name: Node.js CI

on:
  push:
    branches: "nodeenv_test"
  pull_request:
    branches: "nodeenv_test"

jobs:
  build:

    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v3

    - run: ls
    